# Generated by Django 5.0.2 on 2024-03-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': '"Course"',
            },
        ),
    ]
